# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65-ci"

  config.vm.define "ci" do |ci|
  
    ci.vm.hostname = "ci"
  
    ci.vm.network "private_network", ip: "172.31.0.202"
  
  end
  
  config.vm.provider :virtualbox do |p|

    p.customize ["modifyvm", :id, "--memory", 1024]
  end
  
end